// <auto-generated />
namespace SPDC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_field_table_work_experience : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field_table_work_experience));
        
        string IMigrationMetadata.Id
        {
            get { return "202009140326520_add_field_table_work_experience"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
