// <auto-generated />
namespace SPDC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class change_structure_enrollment_status_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_structure_enrollment_status_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202011030434286_change_structure_enrollment_status_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
