// <auto-generated />
namespace SPDC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updaterelationshiprefundtransaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updaterelationshiprefundtransaction));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141612547_update-relationship-refund-transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
